### ISSUE TITLE
no attribute error if not defined in config

### ISSUE THREAD

**Issue by Obsidian500** [NOC-OBG-Autonomy/toolbox#27]
Unless all internal 'substeps' are defined in the config there is an attribute error when the step looks for them.

Using LoadOG1 as an example:

   
```
def run(self):

        source = self.parameters["file_path"]
        print(f"Params: {self.parameters}")
        print(f"[LoadData] Loading {source} OG1")
        # load data from xarray
        self.data = xr.open_dataset(source)

        if self.add_meta:
            self.f_addMeta()

        if self.add_elapsed_time:
            self.f_addElapsedTime()

        if self.add_depth:
            self.f_addDepth(
                lat_label=(
                    self.parameters["lat_label"]
                    if "lat_label" in self.parameters
                    else "LATITUDE"
                )
            )
```

In the cloned config, add_elapsed_time is not specified:

```
- name: "Load OG1"
    parameters:
      file_path: "..." # Path to the input NetCDF file
      add_meta: true # Add metadata to the data
      add_depth: true  # Add depth information to the data
      lat_label: "DEPLOYMENT_LATITUDE"
      diagnostics: true  # Enable diagnostics 
```

This leads to an error when the running `if self.add_elapsed_time:'
It would be good to add something to BaseStep that assumes a substep wont be performed if it isn't specified in the config. I suppose this would also mean that each custom step should have an internal list of possible substeps.
